theme: jekyll-theme-cayman
title: Raising the Volume
description: Amplifying <i>The Soul of Reason</i>
email: soulofreason@nyu.edu
menu:
  - label: Home
  - label: About <i>The Soul of Reason</i>
    anchor: '#about-the-soul-of-reason'
  - label: About the Project
    anchor: '#about-the-project'
  - label: Transcribe-a-thon Events
    link: '/virtual-transcription-events'
