theme: jekyll-theme-cayman
title: Raising the Volume
description: Amplifying <i>The Soul of Reason</i>
menu:
  - label: Home
    link: /
  - label: About the Project
    link: /about-the-project
  - label: About <i>The Soul of Reason</i>
    link: /about-the-collection
  - label: Transcribe-a-thon
    link: /transcription-event
